Render basic graphical objects
BHoM/Rhinoceros_Toolkit pull request #202
Opened 2021-02-10 16:19 UTC by rolyhudson

### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1191

   
### Issues addressed by this PR

Closes #201 

### Test files

### Changelog

### Additional comments

2021-02-24 09:36 UTC, alelom requested changes
Just a few comments

2021-02-24 09:36 UTC, alelom commented on Rhinoceros_Engine/Convert/ToRhino.cs
> +        public static object ToRhino(this IRender render)
This should be private, I think. We should not expose fallback in the UI.

2021-02-24 09:36 UTC, alelom commented on Rhinoceros_Engine/Convert/ToRhino.cs
> +        public static object ToRhino(this IRender render)
If you agree with the above, this method should be moved among the private methods section below the public ones. The header should read "Private methods - fallback"

2021-02-24 09:36 UTC, alelom commented on Rhinoceros_Engine/Convert/ToRhino.cs
> +        public static object ToRhino(this IRender render)
Having had a better look, I can't seem to find any fallback for `ToRhino(IGeometry ...)`!

I think our approach could be to add a single fallback that accepts `IObject` so we cover both `IGeometry` and `IRender`.

2021-02-24 09:36 UTC, alelom commented on Rhinoceros_Engine/Convert/ToRhino.cs
> +        public static Text3d ToRhino(this RenderText renderText)
Could you group these public method under a header that reads "Public methods - IRender" to follow the convention for the methods in this file?

2021-02-24 15:06 UTC, alelom approved these changes
Perfect. Thanks!

2021-02-26 13:12 UTC, rolyhudson commented
@BHoMBot check all

2021-02-26 15:52 UTC, rolyhudson commented
@BHoMBot check-core

2021-02-26 15:53 UTC, rolyhudson commented
@BHoMBot check core

2021-03-02 18:16 UTC, rolyhudson commented
/azp run Rhinoceros_Toolkit.CheckInstaller

2021-03-03 11:16 UTC, merged