Add view capturing capability
BHoM/Rhinoceros_Toolkit pull request #230
Opened 2022-09-20 13:23 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #224

Add capability to capture rhino view.
- Method for capturing currently active view
- Method for capturing all named views

Note that this requires an uptick in the nugets to Rhino 6, as the ViewCapture class used is intern al in rhino 5. There are ways around this for rhino 5 as well, but from testing them, they perform significantly worse and does not give the same level of control.

Before this PR is merged an agreement that this uptick is ok, as it means no more support for rhino 5. @al-fisher @FraserGreenroyd , have discussed this with you before raising this, but noting you in here as well.

### Test files

### Changelog

### Additional comments

2022-09-30 19:07 UTC, michaelhoehn reviewed
Really nice and easy to use! It took a minute to understand the distinction between a DimensionView and a ScaleView since this functionality is unified in a standard Rhino command line prompt, but I think I'm good with the approach generally. I did notice however that there are some performance quirks when using one or the other when exporting a sample image 5000x5000 (likely larger than standard outputs, but I noticed similar behaviors with anything over 3K). 
![image](https://user-images.githubusercontent.com/54593392/193339300-525f80a1-d71b-42b5-82b8-93d22d4b6f52.png)
This is entirely not in our perview as I see it, but good to simply document here it seems capture methodology could have varying nuances between the different types (dimensioned on the left, and scaled on the right). 

I'm happy to provide an approving review when needed, but as noted in the PR and in my comments, we need to discuss our decision to leave Rhino 5 behind in support of these newer features.

2023-01-03 15:42 UTC, michaelhoehn commented on Rhinoceros_Engine/packages.config
> +  <package id="RhinoCommon" version="6.33.20343.16431" targetFramework="net472" />
https://github.com/BHoM/Grasshopper_UI/issues/672

2023-01-03 15:45 UTC, michaelhoehn submitted a review, later dismissed
Very happy with this implementation!

2023-01-04 07:59 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-01-04 17:09 UTC, michaelhoehn commented
@BHoMBot check compliance

2023-01-04 17:11 UTC, michaelhoehn commented
@BHoMBot fix copyright headers ref. 10441140689

2023-01-04 17:13 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 10441140689

2023-01-04 17:16 UTC, FraserGreenroyd requested changes

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_Engine/Compute/CaptureNamedViews.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_Engine/Compute/CaptureView.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/Properties/AssemblyInfo.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("5.0.0.0")]
```suggestion
[assembly: AssemblyVersion("6.0.0.0")]
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("5.3.0.0")]
```suggestion
[assembly: AssemblyFileVersion("6.1.0.0")]
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/ViewCapture/DimensionViewCaptureSettings.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/ViewCapture/IViewCaptureSettings.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:16 UTC, FraserGreenroyd commented on Rhinoceros_oM/ViewCapture/ScaleViewCaptureSettings.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-04 17:18 UTC, michaelhoehn commented
@BHoMBot check compliance

2023-01-04 17:19 UTC, FraserGreenroyd requested changes

2023-01-04 17:19 UTC, FraserGreenroyd commented on Rhinoceros_oM/ViewCapture/ScaleViewCaptureSettings.cs
> +        public double Scale { get; set; } = 2.0;
```suggestion
        public virtual double Scale { get; set; } = 2.0;
```

2023-01-04 17:23 UTC, michaelhoehn commented
@BHoMBot check compliance

2023-01-04 17:24 UTC, FraserGreenroyd commented
@BHoMBot check required

2023-01-04 17:24 UTC, michaelhoehn approved these changes
Go for merge!

2023-01-05 08:52 UTC, IsakNaslundBh commented
@BHoMBot check null-handling

2023-01-05 09:48 UTC, FraserGreenroyd commented
@BHoMBot check null-handling

2023-01-05 09:57 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-01-05 09:59 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check versioning

2023-01-05 11:04 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-01-06 17:09 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-01-07 12:57 UTC, FraserGreenroyd commented
I think I've figured out why versioning is failing - installer would too if we ran it - LadybugTools_Toolkit has a dependency on this toolkit, I think this PR is breaking LadybugTools_Toolkit's ability to compile, thus resulting in versioning issues when the methods/objects don't exist.

I will take another look when back on the laptop to see if I can compile LadybugTools_Toolkit against this branch and if not, work out what the rectification might need to be early in the week with @tg359

2023-01-09 09:50 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-01-09 10:09 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-01-09 10:43 UTC, FraserGreenroyd approved these changes
Now that checks are passing, approving based on previous reviews.

2023-01-09 10:56 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10455686053

2023-01-09 11:21 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2023-01-09 11:22 UTC, merged