Add support for ToRhino for NurbsCurve for Rhino7
BHoM/Rhinoceros_Toolkit pull request #232
Opened 2022-11-15 14:34 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #215

Changing it so that version is checked and version5 convert is called if version is 5. For versions above 5 the same methodology is used and is instead put in the main method. ToRhino6  method remove and versioned to the main method.

### Test files

### Changelog

### Additional comments

2022-11-15 14:44 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2022-11-15 23:50 UTC, FraserGreenroyd requested changes
Very minor code formatting changes.

Otherwise looks good on code review - code has moved from the deleted file to the `ToRhino` file which I think it clean and I like the implementation.

2022-11-15 23:52 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-11-15 23:59 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-11-16 07:06 UTC, IsakNaslundBh commented on Rhinoceros_Engine/Convert/ToRhino.cs
> +            if (bCurve == null) return null;
Fully agree with this. Was a copy paste from the RH6 method. Would have written it as you suggested here.

2022-11-16 07:07 UTC, IsakNaslundBh commented
Happy with the changes @FraserGreenroyd .

2022-11-16 09:14 UTC, FraserGreenroyd approved these changes
Should have remembered to do this bit last night...

2022-11-16 09:15 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-11-16 09:16 UTC, merged